name: "Main Deploy eShop Solution To Azure"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scan-terraform-config-files:
    name: Scan Terraform files with Checov
    uses: ./.github/workflows/01-Scan-Terraform-eShop-Infra.yml
    with:
      WORKING_DIRECTORY: "./Infrastructure"

  gated-build-for-infra:
    name: Gated Build when PR is Raised
    needs: [scan-terraform-config-files]
    uses: ./.github/workflows/02-Gated-Build-eShop-Infra.yml
    with:
      WORKING_DIRECTORY: "./Infrastructure"
    secrets: inherit

  ci-build-for-infra:
    name: CI Build when PR is Merged
    needs: [gated-build-for-infra]
    uses: ./.github/workflows/03-CI-Build-eShop-Infra.yml
    with:
      WORKING_DIRECTORY: "./Infrastructure"
    secrets: inherit
    if: github.ref == 'refs/heads/main'

  deploy-infra-to-azure:
    name: Deploy eShop Infra using Terraform to Azure
    needs: [ci-build-for-infra]
    uses: ./.github/workflows/04-Deploy-eShop-Infra-to-Azure.yml
    with:
      WORKING_DIRECTORY: "./Infrastructure"
    secrets: inherit
    if: github.ref == 'refs/heads/main'
